---
services:
    web:
        build:
            context: "."
        container_name: "bloggy_web"
        restart: "always"
        depends_on:
            - "db"
        ports:
            - "8080:80"
        environment:
            WORDPRESS_DB_HOST: "db"
            WORDPRESS_DB_USER: "bloggy"
            WORDPRESS_DB_PASSWORD: "bloggy"
            WORDPRESS_DB_NAME: "bloggy"
        volumes:
            - "./package/plugin:/var/www/html/wp-content/plugins/bloggy/"
            - "./package/theme:/var/www/html/wp-content/themes/bloggy/"
    db:
        image: "mariadb:10.8.3"
        container_name: "bloggy_db"
        restart: "always"
        environment:
            MARIADB_DATABASE: "bloggy"
            MARIADB_USER: "bloggy"
            MARIADB_PASSWORD: "bloggy"
            MARIADB_RANDOM_ROOT_PASSWORD: "1"
